---
title: "Competitor Analysis"
author: "Fernando Pichardo"
date: '2-5-2023'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Report Overview

The analysis from this report is taken from analyzing 6 videos which captured 5 No Gi matches. The matches were a mix of sub only and points so point specific analysis has been excluded.

## Competition Formats

-   Tournaments - 4
-   Super Match - 1 

## Win/Loss Ratio

-   5 total match's
-   3 Wins
-   2 Loss
-   60% Win Ratio

## Match Breakdown

1. White Lion: Sat down immediately with right leg back and left leg forward attacking opponent right lead leg.  In the match, the opponent attempted a flying kimura while the competitor went for a single leg X. The competitor's right arm was too extended, leading to a back take by the opponent. The opponent held the back take for approximately 20 seconds before transitioning to mount. Match was won in OT by fastest back escape of 45 seconds.

2. NewBreed: The competitor immediately sat down to butterfly guard and tied up with their opponent the entire time. They escaped back quickly and had good leg entries. The competitor almost gave up side control when they wrestled up and had their head and neck exposed which led to losing by guillotine.

3. Copa America: The competitor started against a black belt in butterfly guard and kept going for a sweep but should have stood up. They almost got the sweep from half guard but went back to butterfly and got mounted. The video cut out, but the competitor came on top after a half guard sweep, and it appeared that the opponent was going for a triangle.

4. CSC Match 1: The opponent chose to sit down first, but the competitor used their opponent's left leg to fall back for a leg lock. The match was done in 10 seconds.

5. CSC Match 2: The competitor sat down right away, but the opponent quickly went for rubber guard. The competitor pressured the opponent and got hip bump swept into mount. They had a good triangle escape and were in a position for a body lock pass. The competitor kept using rubber guard to set up moves, but they also had a good escape from a triangle.


## Final Analysis & Reccomendations

### Offense


### Defense

### Key takeaways
